kleaf: add cfg80211 and mac80211 to module_outs
These modules are missing from the module_outs list yet are enabled as
vendor modules. Adding them fixes the follwing build issue:

  ERROR: The following kernel modules are built but not copied. [...]
    "net/wireless/cfg80211.ko",
    "net/mac80211/mac80211.ko",

Bug: 239479410
Test: bazel run //common-modules/virtual-device:virtual_device_x86_64
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I4bb2a2f7f0a5c538c406b95d387b6fce38091957