Revert "virtual-device: aarch64: Enable virtual cpufreq driver"
This reverts commit 45d257dada841289c0fd7373c1586a188c0e5f92.

Reason for revert: Seems to be causing build breakage:
ERROR: modpost: "topology_set_scale_freq_source" [drivers/cpufreq/android-v-virt-cpufreq.ko] undefined!
ERROR: modpost: "cpufreq_get_hw_max_freq" [drivers/cpufreq/android-v-virt-cpufreq.ko] undefined!

Change-Id: Iad7d2f08fa2f5a202a4dbf4ca5c9c478a8c0206c
Signed-off-by: John Stultz <jstultz@google.com>