goldfish_sync.c: fix compiling error on of_device_id and acpi_device_id
need to add linux/mod_devicetable.h header file to fix the following
compiling error:
/data/android/aosp/pure-master/hikey960-kernel/common/../common-modules/virtual-device/goldfish_drivers/goldfish_sync.c:810:56: error: array has incomplete element type 'const struct of_device_id'
static const struct of_device_id goldfish_sync_of_match[] = {
                                                       ^
/data/android/aosp/pure-master/hikey960-kernel/common/include/linux/device.h:308:15: note: forward declaration of 'struct of_device_id'
        const struct of_device_id       *of_match_table;
                     ^
/data/android/aosp/pure-master/hikey960-kernel/common/../common-modules/virtual-device/goldfish_drivers/goldfish_sync.c:816:60: error: array has incomplete element type 'const struct acpi_device_id'
static const struct acpi_device_id goldfish_sync_acpi_match[] = {
                                                           ^
/data/android/aosp/pure-master/hikey960-kernel/common/include/linux/device.h:309:15: note: forward declaration of 'struct acpi_device_id'
        const struct acpi_device_id     *acpi_match_table;
                     ^
2 errors generated.

Test: build test with the following command
    BUILD_CONFIG=common-modules/virtual-device/build.config.goldfish.aarch64 ./build/build.sh -j$(nproc)

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: Ie8129c810c84bc66789f8fed1669fdc2a252af83