virtual-device: Move back virtio_pci_legacy_dev.ko as common module
5a2ba6938c04("virtual-device: Update configs and list of modules")
moved the virtio_pci_legacy_dev.ko from common virtual device module
to ARM64 specific module causing i686 build to fail.

ERROR: The following kernel modules are built but not copied.
Add these lines to the module_outs attribute of
@@//common-modules/virtual-device:virtual_device_i686:
    "drivers/virtio/virtio_pci_legacy_dev.ko",

Fixes: 5a2ba6938c04("virtual-device: Update configs and list of modules")
Bug: 342266893
Test: TH
Change-Id: I496a73a82bcdc823afb46545c43e1880d7b3a727
Signed-off-by: Ramji Jiyani <ramjiyani@google.com>